CONFIG_LOG=y
CONFIG_UART_INTERRUPT_DRIVEN=y
CONFIG_NET_L2_ETHERNET=y
CONFIG_ETH_PIC32CK_GC_GMAC=y
CONFIG_MAIN_STACK_SIZE=4096
CONFIG_NET_CONFIG_SETTINGS=y
CONFIG_NET_CONFIG_MY_IPV4_ADDR="192.168.1.200"
CONFIG_NET_CONFIG_MY_IPV4_GW="192.168.1.1"
CONFIG_NET_CONFIG_MY_IPV4_NETMASK="255.255.255.0"
CONFIG_NET_IPV6=n
CONFIG_NET_SHELL=y
CONFIG_SHELL=y
